/* ============================================================
   Niello ReGreet — Noctalia-synced theme
   Auto-generated by Noctalia user-templates. DO NOT EDIT.
   Edit ~/.config/noctalia/templates/regreet.css.tpl instead.
   ============================================================ */

/* Noctalia color variables — injected at theme-change time */
:root {
  --primary:          {{colors.primary.default.hex}};
  --on-primary:       {{colors.on_primary.default.hex}};
  --secondary:        {{colors.secondary.default.hex}};
  --on-secondary:     {{colors.on_secondary.default.hex}};
  --tertiary:         {{colors.tertiary.default.hex}};
  --surface:          {{colors.surface.default.hex}};
  --surface-variant:  {{colors.surface_variant.default.hex}};
  --on-surface:       {{colors.on_surface.default.hex}};
  --background:       {{colors.background.default.hex}};
  --on-background:    {{colors.on_background.default.hex}};
  --error:            {{colors.error.default.hex}};
  --outline:          {{colors.outline.default.hex}};
}

/* Root window: transparent so cage/wallpaper shows through */
window {
  background: transparent;
}

/* ── Login card ───────────────────────────────────────────── */

box.login-box,
box#main-box {
  background: {{colors.surface.default.hex | set_alpha 0.72}};
  border-radius: 16px;
  border: 1px solid {{colors.outline.default.hex | set_alpha 0.25}};
  box-shadow: 0 8px 32px {{colors.background.default.hex | set_alpha 0.6}};
  padding: 40px 48px;
  margin: auto;
  min-width: 380px;
  backdrop-filter: blur(24px);
  -webkit-backdrop-filter: blur(24px);
}

/* ── Typography ───────────────────────────────────────────── */

label {
  color: {{colors.on_surface.default.hex}};
  font-size: 13px;
}

label.time,
label.date {
  color: {{colors.on_background.default.hex}};
  font-size: 48px;
  font-weight: 300;
  margin-bottom: 4px;
}

label.date-label {
  color: {{colors.on_surface_variant.default.hex}};
  font-size: 14px;
  margin-bottom: 24px;
}

label.error {
  color: {{colors.error.default.hex}};
  font-size: 12px;
}

/* ── Input fields ─────────────────────────────────────────── */

entry {
  background: {{colors.surface_variant.default.hex | set_alpha 0.6}};
  border: 1px solid {{colors.outline.default.hex | set_alpha 0.4}};
  border-radius: 8px;
  color: {{colors.on_surface.default.hex}};
  padding: 10px 14px;
  font-size: 14px;
  caret-color: {{colors.primary.default.hex}};
  min-height: 20px;
}

entry:focus {
  border-color: {{colors.primary.default.hex}};
  background: {{colors.surface_variant.default.hex | set_alpha 0.8}};
  box-shadow: 0 0 0 2px {{colors.primary.default.hex | set_alpha 0.28}};
}

entry::placeholder {
  color: {{colors.on_surface_variant.default.hex | set_alpha 0.5}};
}

/* ── Primary action button (Login) ───────────────────────── */

button.suggested-action,
button#login-button {
  background: {{colors.primary.default.hex}};
  border: none;
  border-radius: 8px;
  color: {{colors.on_primary.default.hex}};
  font-weight: 600;
  font-size: 14px;
  padding: 10px 24px;
  min-height: 20px;
  transition: background 180ms ease;
}

button.suggested-action:hover,
button#login-button:hover {
  background: {{colors.primary.default.hex | lighten 0.08}};
}

button.suggested-action:active,
button#login-button:active {
  background: {{colors.primary.default.hex | darken 0.08}};
}

/* ── Secondary buttons ────────────────────────────────────── */

button {
  background: {{colors.surface_variant.default.hex | set_alpha 0.5}};
  border: 1px solid {{colors.outline.default.hex | set_alpha 0.3}};
  border-radius: 8px;
  color: {{colors.on_surface_variant.default.hex}};
  padding: 8px 16px;
  font-size: 13px;
  transition: background 150ms ease;
}

button:hover {
  background: {{colors.surface_variant.default.hex | set_alpha 0.8}};
}

/* ── Session/user dropdown ────────────────────────────────── */

combobox,
comboboxtext {
  background: {{colors.surface_variant.default.hex | set_alpha 0.5}};
  border: 1px solid {{colors.outline.default.hex | set_alpha 0.3}};
  border-radius: 8px;
  color: {{colors.on_surface_variant.default.hex}};
}

/* ── Spacing ──────────────────────────────────────────────── */

box > * {
  margin-bottom: 12px;
}